import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const BAND_QUESTIONS = [
  {
    id: 'b1_mcq_1',
    type: 'mcq',
    skill: 'Greetings',
    band: 1,
    question: 'What does નમસ્તે mean?',
    gujaratiText: 'નમસ્તે',
    options: ['Hello', 'Goodbye', 'Thanks', 'Sorry'],
    answer: 'Hello',
    answerGujarati: 'નમસ્તે',
    explanation: 'નમસ્તે is “hello”; a respectful greeting.',
    pronunciationTarget: null,
  },
  {
    id: 'b1_mcq_2',
    type: 'mcq',
    skill: 'Numbers',
    band: 1,
    question: 'How do you say the number 3 in Gujarati?',
    gujaratiText: 'એક · બે · ત્રણ · ચાર',
    options: ['એક', 'બે', 'ત્રણ', 'ચાર'],
    answer: 'ત્રણ',
    answerGujarati: 'ત્રણ',
    explanation: 'ત્રણ is three.',
    pronunciationTarget: null,
  },
  {
    id: 'b1_mcq_3',
    type: 'mcq',
    skill: 'Greetings',
    band: 1,
    question: 'What does કેમ છો mean?',
    gujaratiText: 'કેમ છો',
    options: ['How are you', 'Thank you', 'Good morning', 'Goodbye'],
    answer: 'How are you',
    answerGujarati: 'કેમ છો',
    explanation: 'Literally “how are you?” — કેમ छो?',
    pronunciationTarget: null,
  },
  {
    id: 'b1_pr_1',
    type: 'pronunciation',
    skill: 'Pronunciation',
    band: 1,
    question: 'Say this word out loud',
    gujaratiText: 'નમસ્તે',
    options: null,
    answer: null,
    answerGujarati: 'નમસ્તે',
    explanation: 'namaste — stress the second syllable lightly.',
    pronunciationTarget: 'namaste',
  },
  {
    id: 'b1_mcq_4',
    type: 'mcq',
    skill: 'Basics',
    band: 1,
    question: 'How do you say Yes in Gujarati?',
    gujaratiText: 'હા · ના',
    options: ['હા', 'ના', 'સારું', 'ઠીક'],
    answer: 'હા',
    answerGujarati: 'હા',
    explanation: 'હા means yes.',
    pronunciationTarget: null,
  },
  {
    id: 'b2_mcq_1',
    type: 'mcq',
    skill: 'Gender',
    band: 2,
    question: 'છોકરો (chhokro) means boy. What gender is it?',
    gujaratiText: 'છોકરો',
    options: ['Masculine', 'Feminine', 'Neuter', 'None'],
    answer: 'Masculine',
    answerGujarati: 'છોકરો',
    explanation: 'Masculine nouns often end in ઓ.',
    pronunciationTarget: null,
  },
  {
    id: 'b2_mcq_2',
    type: 'mcq',
    skill: 'Pronouns',
    band: 2,
    question: "Which pronoun means 'I' in Gujarati?",
    gujaratiText: 'હું · તમે · તે',
    options: ['તમે', 'તે', 'હું', 'અમે'],
    answer: 'હું',
    answerGujarati: 'હું',
    explanation: 'હું is first person singular.',
    pronunciationTarget: null,
  },
  {
    id: 'b2_mcq_3',
    type: 'mcq',
    skill: 'Gender',
    band: 2,
    question: 'છોકરી ends in -i. What gender is it?',
    gujaratiText: 'છોકરી',
    options: ['Feminine', 'Masculine', 'Neuter', 'Mixed'],
    answer: 'Feminine',
    answerGujarati: 'છોકરી',
    explanation: 'Many feminine nouns end in ઈ.',
    pronunciationTarget: null,
  },
  {
    id: 'b2_pr_1',
    type: 'pronunciation',
    skill: 'Pronouns',
    band: 2,
    question: 'Say this pronoun',
    gujaratiText: 'હું',
    options: null,
    answer: null,
    answerGujarati: 'હું',
    explanation: 'hu — short “u” vowel.',
    pronunciationTarget: 'hu',
  },
  {
    id: 'b2_mcq_4',
    type: 'mcq',
    skill: 'Nouns',
    band: 2,
    question: 'What does ઘર mean and what gender is it?',
    gujaratiText: 'ઘર',
    options: ['House/Neuter', 'Boy/Masculine', 'Girl/Feminine', 'Water/Neuter'],
    answer: 'House/Neuter',
    answerGujarati: 'ઘર (નપુંસક)',
    explanation: 'ઘર is neuter house/home.',
    pronunciationTarget: null,
  },
  {
    id: 'b3_mcq_1',
    type: 'mcq',
    skill: 'Postpositions',
    band: 3,
    question: 'ઘરમાં means what?',
    gujaratiText: 'ઘરમાં',
    options: ['In the house', 'On the house', 'From the house', 'Near the house'],
    answer: 'In the house',
    answerGujarati: 'ઘરમાં',
    explanation: 'માં marks location “in/on inside”.',
    pronunciationTarget: null,
  },
  {
    id: 'b3_mcq_2',
    type: 'mcq',
    skill: 'Postpositions',
    band: 3,
    question: 'Which postposition means FROM in Gujarati?',
    gujaratiText: 'માં · પર · થી · ને',
    options: ['માં', 'પર', 'થી', 'ને'],
    answer: 'થી',
    answerGujarati: 'થી',
    explanation: 'થી conveys source/from.',
    pronunciationTarget: null,
  },
  {
    id: 'b3_mcq_3',
    type: 'mcq',
    skill: 'Verbs',
    band: 3,
    question: 'તે ડૉક્ટર છે means?',
    gujaratiText: 'તે ડૉક્ટર છે',
    options: ['He is a doctor', 'She was a doctor', 'He will be a doctor', 'I am a doctor'],
    answer: 'He is a doctor',
    answerGujarati: 'તે ડૉક્ટર છે',
    explanation: 'Present copula છે marks “is”.',
    pronunciationTarget: null,
  },
  {
    id: 'b3_pr_1',
    type: 'pronunciation',
    skill: 'Phrases',
    band: 3,
    question: 'Say this phrase',
    gujaratiText: 'કેમ છો',
    options: null,
    answer: null,
    answerGujarati: 'કેમ છો',
    explanation: 'kem cho — how are you?',
    pronunciationTarget: 'kem cho',
  },
  {
    id: 'b3_mcq_4',
    type: 'mcq',
    skill: 'Tense',
    band: 3,
    question: 'What is the past tense of છે (is)?',
    gujaratiText: 'છું · હતો',
    options: ['હતો/હતી', 'હશે', 'ছું', 'હોય'],
    answer: 'હતો/હતી',
    answerGujarati: 'હતો/હતી',
    explanation:
      'હતો and હતી are common past-tense patterns that agree with gendered subjects.',
    pronunciationTarget: null,
  },
  {
    id: 'b4_mcq_1',
    type: 'mcq',
    skill: 'Syntax',
    band: 4,
    question: 'Gujarati follows which word order?',
    gujaratiText: 'વાક્યરચના',
    options: ['SOV', 'SVO', 'VSO', 'OVS'],
    answer: 'SOV',
    answerGujarati: 'SOV',
    explanation: 'Subject–object–verb is the default scaffolding.',
    pronunciationTarget: null,
  },
  {
    id: 'b4_mcq_2',
    type: 'mcq',
    skill: 'Adjectives',
    band: 4,
    question: 'સારો છોકરો means good boy. How do you say good girl?',
    gujaratiText: 'સારો છોકરો · સારી છોકરી',
    options: ['સારી છોકરી', 'સારો છોકરી', 'સારું છોકરી', 'સારા છોકરી'],
    answer: 'સારી છોકરી',
    answerGujarati: 'સારી છોકરી',
    explanation: 'Adjective સારું agrees: સારી with feminine છોકરી.',
    pronunciationTarget: null,
  },
  {
    id: 'b4_mcq_3',
    type: 'mcq',
    skill: 'Translation',
    band: 4,
    question: 'Translate: I drink water',
    gujaratiText: 'પાણી પીવું',
    options: [
      'હું પાણી પીઉ છું',
      'હું પાણી ખાઉ છું',
      'તે પાણી પીવે છે',
      'અમે પાણી પીઉ છું',
    ],
    answer: 'હું પાણી પીઉ છું',
    answerGujarati: 'હું પાણી પીઉ છું',
    explanation: 'First person + present habitual પીઉ છું.',
    pronunciationTarget: null,
  },
  {
    id: 'b4_pr_1',
    type: 'pronunciation',
    skill: 'Sentence',
    band: 4,
    question: 'Say this sentence',
    gujaratiText: 'હું ભૂખ્યો છું',
    options: null,
    answer: null,
    answerGujarati: 'હું ભૂખ્યો છું',
    explanation: 'hu bhukhyo chhu — I am hungry (masc speaker).',
    pronunciationTarget: 'hu bhukhyo chhu',
  },
  {
    id: 'b4_mcq_4',
    type: 'mcq',
    skill: 'Agreement',
    band: 4,
    question: 'મોટો means big (masc). What is big in neuter form?',
    gujaratiText: 'મોટું',
    options: ['મોટું', 'મોટી', 'મોટા', 'મોટે'],
    answer: 'મોટું',
    answerGujarati: 'મોટું',
    explanation: 'Neuter agreement uses મોટું.',
    pronunciationTarget: null,
  },
  {
    id: 'b5_mcq_1',
    type: 'mcq',
    skill: 'Inclusive we',
    band: 5,
    question: 'Translate: We are learning Gujarati (including listener)',
    gujaratiText: 'આપણે · અમે',
    options: [
      'આપણે ગુજરાતી શીખીએ છીએ',
      'અમે ગુજરાતી શીખીએ છીએ',
      'તેઓ ગુજરાતી શીખે છે',
      'હું ગુજરાતી શીખું છું',
    ],
    answer: 'આપણે ગુજરાતી શીખીએ છીએ',
    answerGujarati: 'આપણે ગુજરાતી શીખીએ છીએ',
    explanation: 'આપણે signals “we” that includes you, the listener.',
    pronunciationTarget: null,
  },
  {
    id: 'b5_mcq_2',
    type: 'mcq',
    skill: 'Pronouns',
    band: 5,
    question: 'What is the difference between અમે and આપણે?',
    gujaratiText: 'અમે · આપણે',
    options: [
      'અમે excludes listener આપણે includes listener',
      'They mean the same thing',
      'અમે is formal આપણે is informal',
      'અમે is plural આપણે is singular',
    ],
    answer: 'અમે excludes listener આપણે includes listener',
    answerGujarati: 'અમે / આપણે',
    explanation: 'અમે is exclusive we; આપણે is inclusive.',
    pronunciationTarget: null,
  },
  {
    id: 'b5_mcq_3',
    type: 'mcq',
    skill: 'Grammar',
    band: 5,
    question: 'નો ની નું are all forms of which postposition?',
    gujaratiText: 'નો ની નું',
    options: ['Possessive of', 'In', 'From', 'To'],
    answer: 'Possessive of',
    answerGujarati: 'સંબંધ દર્શક',
    explanation: 'These mark possession agreement with noun gender.',
    pronunciationTarget: null,
  },
  {
    id: 'b5_pr_1',
    type: 'pronunciation',
    skill: 'Fluency',
    band: 5,
    question: 'Say this full sentence',
    gujaratiText: 'ભારત મારો દેશ છે',
    options: null,
    answer: null,
    answerGujarati: 'ભારત મારો દેશ છે',
    explanation: 'bharat maro desh chhe',
    pronunciationTarget: 'bharat maro desh chhe',
  },
  {
    id: 'b5_mcq_4',
    type: 'mcq',
    skill: 'Reading',
    band: 5,
    question: 'તે પુસ્તક વાંચે છે translates to?',
    gujaratiText: 'તે પુસ્તક વાંચે છે',
    options: ['She reads a book', 'He ate a book', 'They will read', 'I read books'],
    answer: 'She reads a book',
    answerGujarati: 'તે પુસ્તક વાંચે છે',
    explanation: 'Present habitual reading fits this gloss.',
    pronunciationTarget: null,
  },
]

const PLACEMENT_QUESTIONS = [
  {
    id: 'pl_b1_1',
    type: 'mcq',
    skill: 'Greetings',
    band: 1,
    question: 'What does નમસ્તે mean?',
    gujaratiText: 'નમસ્તે',
    options: ['Hello', 'Goodbye', 'Thanks', 'Sorry'],
    answer: 'Hello',
    answerGujarati: 'નમસ્તે',
    explanation: 'નમસ્તે is a common greeting meaning hello.',
    pronunciationTarget: null,
  },
  {
    id: 'pl_b1_2',
    type: 'pronunciation',
    skill: 'Numbers',
    band: 1,
    question: 'Say this number word out loud.',
    gujaratiText: 'ત્રણ',
    options: null,
    answer: null,
    answerGujarati: 'ત્રણ',
    explanation: 'Pronunciation guide: tran',
    pronunciationTarget: 'tran',
  },
  {
    id: 'pl_b2_1',
    type: 'mcq',
    skill: 'Pronouns',
    band: 2,
    question: 'છોકરો (chhokro) means boy. What gender is it?',
    gujaratiText: 'છોકરો',
    options: ['Masculine', 'Feminine', 'Neuter', 'None'],
    answer: 'Masculine',
    answerGujarati: 'છોકરો',
    explanation: '-o noun endings are typically masculine.',
    pronunciationTarget: null,
  },
  {
    id: 'pl_b2_2',
    type: 'mcq',
    skill: 'Gender',
    band: 2,
    question: 'છોકરી ends in -i. What gender is it?',
    gujaratiText: 'છોકરી',
    options: ['Feminine', 'Masculine', 'Neuter', 'Mixed'],
    answer: 'Feminine',
    answerGujarati: 'છોકરી',
    explanation: '-i endings often mark feminine nouns.',
    pronunciationTarget: null,
  },
  {
    id: 'pl_b3_1',
    type: 'mcq',
    skill: 'Postpositions',
    band: 3,
    question: 'ઘરમાં means what?',
    gujaratiText: 'ઘરમાં',
    options: ['In the house', 'On the house', 'From the house', 'Near the house'],
    answer: 'In the house',
    answerGujarati: 'ઘરમાં',
    explanation: 'માં often means in or inside.',
    pronunciationTarget: null,
  },
  {
    id: 'pl_b3_2',
    type: 'pronunciation',
    skill: 'Phrases',
    band: 3,
    question: 'Say this phrase clearly.',
    gujaratiText: 'કેમ છો',
    options: null,
    answer: null,
    answerGujarati: 'કેમ છો',
    explanation: 'kem cho — how are you',
    pronunciationTarget: 'kem cho',
  },
  {
    id: 'pl_b4_1',
    type: 'mcq',
    skill: 'Syntax',
    band: 4,
    question: 'Gujarati follows which word order?',
    gujaratiText: 'હું જમી લઉ છું.',
    options: ['SOV', 'SVO', 'VSO', 'OVS'],
    answer: 'SOV',
    answerGujarati: 'SOV માળખું',
    explanation: 'Subject–Object–Verb is typical in Gujarati.',
    pronunciationTarget: null,
  },
  {
    id: 'pl_b4_2',
    type: 'mcq',
    skill: 'Adjectives',
    band: 4,
    question: 'મોટો means big (masc). What is big in neuter form?',
    gujaratiText: 'મોટો / મોટું',
    options: ['મોટું', 'મોટી', 'મોટા', 'મોટે'],
    answer: 'મોટું',
    answerGujarati: 'મોટું',
    explanation: 'Neuter adjectives commonly use મોટું.',
    pronunciationTarget: null,
  },
  {
    id: 'pl_b5_1',
    type: 'mcq',
    skill: 'Inclusive pronouns',
    band: 5,
    question: 'What is the difference between અમે and આપણે?',
    gujaratiText: 'અમે · આપણે',
    options: [
      'અમે excludes listener આપણે includes listener',
      'They mean the same thing',
      'અમે is formal આપણે is informal',
      'અમે is plural આપણે is singular',
    ],
    answer: 'અમે excludes listener આપણે includes listener',
    answerGujarati: 'અમે સાંભાળનારને બાકાત; આપણે સાથે સમાવે.',
    explanation: 'અમે is “we” excluding the listener; આપણે includes the listener.',
    pronunciationTarget: null,
  },
  {
    id: 'pl_b5_2',
    type: 'mcq',
    skill: 'Reading',
    band: 5,
    question: 'તે પુસ્તક વાંચે છે translates to?',
    gujaratiText: 'તે પુસ્તક વાંચે છે',
    options: ['She reads a book', 'He ate a book', 'They will read', 'I read books'],
    answer: 'She reads a book',
    answerGujarati: 'તે પુસ્તક વાંચે છે',
    explanation: 'Context often clarifies gender; this is a present habitual reading sense.',
    pronunciationTarget: null,
  },
]

function generateSQL(table, data) {
  let sql = "-- Insert into " + table + "\\n"
  
  data.forEach((q) => {
    const content = JSON.stringify({
      question: q.question,
      gujaratiText: q.gujaratiText,
      options: q.options,
      answer: q.answer,
      answerGujarati: q.answerGujarati,
      explanation: q.explanation,
      pronunciationTarget: q.pronunciationTarget
    })
    
    // escape single quotes
    const escapedContent = content.replace(/'/g, "''")
    const id = q.id
    const type = q.type
    const skill = q.skill.replace(/'/g, "''")
    const band = q.band
    
    sql += "INSERT INTO public." + table + " (id, type, skill, band, content) VALUES ('" + id + "', '" + type + "', '" + skill + "', " + band + ", '" + escapedContent + "');\\n"
  })
  
  return sql
}

const finalSql = generateSQL('questions', BAND_QUESTIONS) + "\\n\\n" + generateSQL('placement_questions', PLACEMENT_QUESTIONS)
fs.writeFileSync(path.join(__dirname, 'backend/supabase/migrations/002_seed_questions.sql'), finalSql)
